const canvas=document.querySelector("#docCanvas"),ctx=canvas.getContext("2d"),emptyState=document.querySelector("#emptyState");
let img=null,activeField="containerNumber",drawing=false,start=null;
let boxes=JSON.parse(localStorage.getItem("earOcrBoxesV2")||"{}");
const COLORS={containerNumber:"#ef4444",sealNo:"#22c55e",booking:"#3b82f6"};
const LABELS={containerNumber:"1 CONTAINER NUMBER",sealNo:"2 SEAL NO",booking:"3 BOOKING"};

function saveBoxes(){localStorage.setItem("earOcrBoxesV2",JSON.stringify(boxes));updateSummary()}
function updateSummary(){for(const k of Object.keys(LABELS)){const b=boxes[k];document.querySelector(`#box-${k}`).textContent=b?`x ${(b.x*100).toFixed(1)}% · y ${(b.y*100).toFixed(1)}% · w ${(b.w*100).toFixed(1)}% · h ${(b.h*100).toFixed(1)}%`:"ยังไม่กำหนด"}}
function redraw(){if(!img)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);for(const [k,b] of Object.entries(boxes)){const x=b.x*canvas.width,y=b.y*canvas.height,w=b.w*canvas.width,h=b.h*canvas.height;ctx.save();ctx.strokeStyle=COLORS[k];ctx.lineWidth=Math.max(2,canvas.width/400);ctx.fillStyle=COLORS[k]+"20";ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.fillStyle=COLORS[k];ctx.font=`bold ${Math.max(14,canvas.width/45)}px Arial`;ctx.fillText(LABELS[k],x+5,Math.max(20,y-6));ctx.restore()}}
document.querySelectorAll(".field").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".field").forEach(x=>x.classList.remove("active"));btn.classList.add("active");activeField=btn.dataset.field;document.querySelector("#message").textContent=`กำลังเลือก: ${LABELS[activeField]} — ลากกรอบเฉพาะค่าจริง`}));
document.querySelector("#fileInput").addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;document.querySelector("#fileName").textContent=file.name;const loaded=new Image();loaded.onload=()=>{img=loaded;emptyState.style.display="none";const maxW=1100,scale=Math.min(1,maxW/loaded.width);canvas.width=Math.round(loaded.width*scale);canvas.height=Math.round(loaded.height*scale);redraw()};loaded.src=URL.createObjectURL(file)});
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener("pointerdown",e=>{if(!img)return;drawing=true;start=point(e);canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener("pointermove",e=>{if(!drawing||!start)return;redraw();const p=point(e);ctx.save();ctx.strokeStyle=COLORS[activeField];ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.strokeRect(start.x,start.y,p.x-start.x,p.y-start.y);ctx.restore()});
canvas.addEventListener("pointerup",e=>{if(!drawing||!start)return;drawing=false;const p=point(e),x=Math.min(start.x,p.x),y=Math.min(start.y,p.y),w=Math.abs(p.x-start.x),h=Math.abs(p.y-start.y);start=null;if(w<10||h<10){redraw();return}boxes[activeField]={x:x/canvas.width,y:y/canvas.height,w:w/canvas.width,h:h/canvas.height};saveBoxes();redraw()});
document.querySelector("#clearBoxes").addEventListener("click",()=>{boxes={};saveBoxes();redraw()});

function crop(field){const b=boxes[field];if(!b||!img)return null;const sx=Math.round(b.x*img.naturalWidth),sy=Math.round(b.y*img.naturalHeight),sw=Math.round(b.w*img.naturalWidth),sh=Math.round(b.h*img.naturalHeight),scale=5,c=document.createElement("canvas");c.width=Math.max(1,sw*scale);c.height=Math.max(1,sh*scale);const cc=c.getContext("2d",{willReadFrequently:true});cc.imageSmoothingEnabled=true;cc.imageSmoothingQuality="high";cc.drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height);return c}
function preprocess(source,mode){const c=document.createElement("canvas");c.width=source.width;c.height=source.height;const cc=c.getContext("2d",{willReadFrequently:true});cc.drawImage(source,0,0);if(mode==="original")return c;const im=cc.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=Math.round(d[i]*.299+d[i+1]*.587+d[i+2]*.114);let v=g;if(mode==="contrast")v=Math.max(0,Math.min(255,(g-128)*2.5+128));if(mode==="threshold")v=g<190?0:255;d[i]=d[i+1]=d[i+2]=v}cc.putImageData(im,0,0);return c}
const clean=v=>String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"");
function repairContainer(v){const raw=clean(v);for(let i=0;i<=raw.length-11;i++){const s=raw.slice(i,i+11),p=s.slice(0,4).replace(/0/g,"O").replace(/1/g,"I").replace(/5/g,"S").replace(/8/g,"B"),n=s.slice(4).replace(/O/g,"0").replace(/[IL]/g,"1").replace(/Z/g,"2").replace(/S/g,"5").replace(/B/g,"8").replace(/G/g,"6"),candidate=p+n;if(/^[A-Z]{4}\d{7}$/.test(candidate))return candidate}return""}
function parse(field,text){if(field==="containerNumber")return repairContainer(text);const tokens=(String(text||"").toUpperCase().match(/[A-Z0-9][A-Z0-9\-_/]{4,20}/g)||[]).map(clean).filter(x=>/[A-Z]/.test(x)&&/\d/.test(x));if(field==="sealNo")return tokens.filter(x=>x.length>=7&&x.length<=14).sort((a,b)=>Math.abs(a.length-9)-Math.abs(b.length-9))[0]||"";if(field==="booking")return tokens.filter(x=>x.length>=8&&x.length<=16).sort((a,b)=>b.length-a.length)[0]||"";return""}
async function readField(worker,field,c){const passes=[["original",7],["contrast",7],["threshold",7],["contrast",8]],results=[];for(const [mode,psm] of passes){await worker.setParameters({tessedit_pageseg_mode:String(psm),preserve_interword_spaces:"1",user_defined_dpi:"300",tessedit_char_whitelist:"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_/"});const r=await worker.recognize(preprocess(c,mode));results.push({raw:r.data.text||"",value:parse(field,r.data.text||""),conf:Number(r.data.confidence||0)})}const votes=new Map();for(const r of results){if(!r.value)continue;const old=votes.get(r.value)||{value:r.value,count:0,conf:0};old.count++;old.conf+=r.conf;votes.set(r.value,old)}const ranked=[...votes.values()].sort((a,b)=>b.count-a.count||b.conf-a.conf);return{value:ranked[0]?.value||"",raw:results.map(x=>x.raw.trim()).filter(Boolean).join(" | ")}}
document.querySelector("#testBtn").addEventListener("click",async()=>{if(!img){alert("กรุณาเลือกรูป EAR ก่อน");return}const missing=Object.keys(LABELS).filter(k=>!boxes[k]);if(missing.length){alert("กรุณากำหนดกรอบทั้ง 3 จุดก่อน");return}document.querySelector("#progressWrap").classList.remove("hidden");const bar=document.querySelector("#bar"),text=document.querySelector("#progressText"),worker=await Tesseract.createWorker("eng",1,{logger:m=>{if(m.status==="recognizing text")bar.style.width=`${Math.round((m.progress||0)*100)}%`}});try{let i=0;for(const field of ["containerNumber","sealNo","booking"]){i++;text.textContent=`กำลังอ่าน ${LABELS[field]} (${i}/3)`;const result=await readField(worker,field,crop(field));document.querySelector(`#out-${field}`).value=result.value;document.querySelector(`#raw-${field}`).textContent=result.raw?`OCR: ${result.raw}`:"OCR ไม่พบข้อความ"}bar.style.width="100%";text.textContent="อ่านครบแล้ว"}finally{await worker.terminate()}});

updateSummary();
